# file: btrfs-layout-flat/create.yml
---
- debug:
    msg: "creating a btrfs filesystem with flat subvolume layout"


- name: create btrfs filesystem on system partition
  filesystem:
    dev: "{{ device }}"
    fstype: btrfs
    force: no

# mount system partition to create the btrfs filesystem with the desired subvolumes
# - name: mount the mapped device to create subvolumes and directories
#   command: mount -t btrfs -o compress=zstd {{ device }} {{ mountpoint }}

- name: mount the mapped device to create subvolumes and directories
  mount:
    src: "{{ device }}"
    path: "{{ mountpoint }}"
    fstab: "{{ tmpdir }}/fstab-discard"
    fstype: btrfs
    opts: compress=zstd
    state: mounted

# top-level subvolumes to be mounted
- name: create the btrfs root subvolume
  command: btrfs subvolume create {{ mountpoint }}/@
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc == 0

- name: create the btrfs home subvolume
  command: btrfs subvolume create {{ mountpoint }}/@home
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc == 0

- name: create the btrfs snapshots subvolume
  command: btrfs subvolume create {{ mountpoint }}/@snapshots
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc == 0

# directories
- name: create /@/.snapshots
  file: state=directory path="{{ mountpoint }}/@/.snapshots"

- name: create /@/var/cache/pacman
  file: state=directory path="{{ mountpoint }}/@/var/cache/pacman"

- name: create /@/home
  file: state=directory path="{{ mountpoint }}/@/home"

# subvolumes as directories, which are not directly under root so not to be snapshotted
- name: create the btrfs pacman cache subvolume
  command: btrfs subvolume create {{ mountpoint }}/@/var/cache/pacman/pkg
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc == 0

- name: create the btrfs abs subvolume
  command: btrfs subvolume create {{ mountpoint }}/@/var/abs
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc == 0

- name: create the btrfs tmp subvolume
  command: btrfs subvolume create {{ mountpoint }}/@/var/tmp
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc == 0

# unmounting the partition to remount it with the subvolumes
- name: unmount the system partition
  mount: state=unmounted path="{{ mountpoint }}"
