# file: sudoers/tasks/main.yml
# allows wheel group to use sudo
---

- name: install sudo
  pacman:
    name: sudo
    state: present

- name: set /etc/sudoers
  copy:
    src: etc/sudoers
    dest: /etc/sudoers
    force: yes
    mode: '0440'
    owner: root
    group: root
