# file: AutoarchDesktop.yml
# Playbook to setup an xorg desktop

- hosts: arch_desktops
  user: root
  tasks:
    ## preparation
    - name: create .ssh directory
      file:
        state: directory
        path: "/home/{{ admin_user }}/.ssh"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0700'

    - include_role:
        name: conf_user_git

    - name: update package cache and upgrade system (pacman -Syu)
      pacman:
        update_cache: yes
        upgrade: yes

    # ## drivers
    - name: install video drivers
      pacman:
        name:
          - "{{ desktop_video_driver }}"
          - mesa
        state: present

    - name: install PulseAudio
      pacman:
        name:
          - "extra/pulseaudio"
          - pulsemixer
        state: present

    ## software
    - name: install xorg and graphical environment software
      pacman:
        name:
          - xorg
          - xorg-xinit
          - "i3-gaps"
          - termite
          - conky
          - firefox
          - dmenu
          - keepass

    ## input configuration
    - include_role:
        name: input_dev_conf
