# file: AutoarchProgs.yml
# Playbook to setup the rest of my programs

- hosts: arch_desktops
  user: root
  vars:
    aur_sync: "sudo -u builder aur sync -d custom --noconfirm --noview"
    pac_args: "--noconfirm --quiet --noprogressbar"
  tasks:

    - name: update package cache (pacman -Sy)
      pacman:
        update_cache: yes
        update_cache_extra_args: "{{ pac_args }}"

    - name: churn through program list
      pacman:
        extra_args: "{{ pac_args }}"
        name:
          - "core/man-pages"
          - mpd
          - vlc
          - seahorse
          - "community/openssh-askpass"
          - "community/lxqt-openssh-askpass"
          - kgpg
          - encfs
          - xca
          - flameshot
          - xkcdpass
          - nmap
          - transmission-gtk
          - transmission-cli
          - dunst
          - "extra/graphviz"
          - "community/torbrowser-launcher"
          - "community/offlineimap"
          - "community/nullmailer"
          - "extra/python-pip"
          - "community/zathura"
          - "community/zathura-pdf-poppler"
          - "extra/zip"
          - "extra/unzip"
          - "extra/texlive-most"
          - "community/yad"  # location picker
          - "extra/smbclient"
          - "extra/unrar"
          - "extra/libreoffice-fresh"
          - "community/simple-scan"
          # - "community/virt-manager"
          # - "community/lxc"
          # - "community/lxcfs"
          # - "community/lxd"
          - "community/packer"
          - "community/pyenv"
          - "community/wmctrl"
