# file: AutoarchSystemConfig.yml
# configures all archlinux non-essential system level services

- hosts: arch_desktops
  user: root
  tasks:
    # firewall
    - include_role:
        name: archpkg_firewall_desktop
    # cpu frequency scaling
    - include_role:
        name: archpkg_cpupower
      when: is_mobile
    # NTP daemon
    - include_role:
        name: archpkg_chrony
      when: is_mobile
    # systemd-logind.conf: simple acpi power management and more
    - include_role:
        name: logind_haltonhiber
