# file: AutoarchSystemConfig.yml
# configures all archlinux non-essential system level services

- hosts: arch_desktops
  user: root
  tasks:
    - include_role:
        name: archpkg_firewall_desktop
