# file: AutoarchSystemConfig.yml
# configures all archlinux non-essential system level services

- hosts: arch_desktops
  user: root
  vars:
    pac_args: "--noconfirm --quiet --noprogressbar"
  tasks:
    ## services and programs
    - name: update package cache and upgrade system (pacman -Syu)
      pacman:
        update_cache: yes
        upgrade: yes
        update_cache_extra_args: "{{ pac_args }}"
        upgrade_extra_args: "{{ pac_args }}"
        extra_args: "{{ pac_args }}"
    # firewall
    - include_role:
        name: archpkg_firewall_desktop
    # cpu frequency scaling
    - include_role:
        name: archpkg_cpupower
      when: is_mobile
    # NTP daemon
    - include_role:
        name: archpkg_chrony
      when: is_mobile
    # systemd-logind.conf: simple acpi power management and more
    - include_role:
        name: logind_haltonhiber
    # shells
    - name: install zsh
      pacman:
        name: "extra/zsh"
        state: present
        extra_args: "{{ pac_args }}"

    - name: install fish shell
      pacman:
        name: "community/fish"
        state: present
        extra_args: "{{ pac_args }}"

    ## users and privileges

    # members of the wheel group may use sudo with their own pw
    - include_role:
        name: sudoers

    - name: create main user with admin privileges
      user:
        name: "{{ admin_user }}"
        state: present
        shell: /bin/zsh
        create_home: yes
        skeleton: "/dev/null"
        home: "/home/{{ admin_user }}"
        groups: sys,log,games,network,rfkill,systemd-journal,uucp,wheel,adm

    - name: set main user password
      shell: |
        echo -n '{{ admin_user }}:{{ admin_pw }}'  | chpasswd --encrypted

    # why must I do this?
    - name: change ownership of admin_user home to the user
      file:
        path: "/home/{{ admin_user }}"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0740'

    # arch user repository
    - include_role:
        name: arch_aurutils

    # finally
    - name: install various tools and depenencies
      command: "pacman {{ pac_args }} -S devtools base-devel htop tree"
