# file: setup-LUKS.yml
# sets up LUKS on `device`. Passphrase must me stored inside `passphrase` (path).
# `keyfile` is required for alternative unlocking
---

# transfer keyfiles
- block:
    # for interactive input to grub
    - name: transfer passphrase file
      copy:
        src: "{{ luks_passphrase }}"
        dest: "{{ tmpdir0 }}"
        mode: '0600'
        decrypt: yes

    # to be embedded in the initramfs
    - name: transfer keyfile
      copy:
        src: "{{ luks_keyfile }}"
        dest: "{{ tmpdir0 }}"
        mode: '0600'
        decrypt: yes
  when: not luks_interactive

# create keyfiles
- block:
    - name: make temporary luks passphrase keyfile
      template:
        src: passphrase.j2
        dest: "{{ tmpdir0 }}/luks_passphrase"
        force: yes
        mode: '0600'
    - name: create initramfs crypto_keyfile.bin
      command: "dd if=/dev/urandom of={{ tmpdir0 }}/crypto_keyfile.bin bs=512 count=4"
  when: luks_interactive


# for idempotency
- name: check if LUKS is present on system partition
  command: lsblk -lin {{ device }} -o FSTYPE
  register: fstype_syspart
  ignore_errors: True

- name: if LUKS is present, check if the container can be opened with the key
  command: cryptsetup luksOpen --test-passphrase --key-file {{ tmpdir0 }}/luks_passphrase {{ device }}
  when: fstype_syspart.stdout == 'crypto_LUKS'
  ignore_errors: True
  register: result

- name: if LUKS is not present or cannot be opened, wipe the system partition and create a new LUKS container
  block:
    - command: wipefs -af {{ device }}
    ## does only luks2, need luks1 for GRUB
    # - luks_device:
    #     device: "{{ device }}"
    #     state: present
    #     keyfile: "{{ keyfile }}"
    ## create luks container
    - command: cryptsetup --batch-mode --type luks1 --cipher aes-xts-plain64 --key-size 256 --hash sha256 --iter-time 2000 --key-file {{ tmpdir0 }}/luks_passphrase luksFormat {{device}}
    ## add keyfile to another slot
    - command: cryptsetup --batch-mode --type luks1 --key-file {{ tmpdir0 }}/luks_passphrase luksAddKey {{ device }} {{ tmpdir0 }}/crypto_keyfile.bin
  when: (result is failed) or (result is skipped)
