# file: conf_user_git/tasks/main.yml
# configures user git and checks out the dotfiles repo
---

- name: copy git config
  copy:
    src: "{{ github_conf }}"
    dest: "/home/{{ admin_user }}/.ssh/config"
    force: yes
    decrypt: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0600'
    directory_mode: '0700'

- name: copy github private key
  copy:
    src: "{{ github_pk }}"
    dest: "/home/{{ admin_user }}/.ssh/github"
    force: yes
    decrypt: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0600'
    directory_mode: '0700'

- name: delete all conflicting files (e.g. ~/.bash*)
  file:
    path: "{{ item }}"
    state: absent
    force: yes
  with_fileglob:
    - "/home/{{ admin_user }}/.bash*"
    - "/home/{{ admin_user }}/.Xresources"
    - "/home/{{ admin_user }}/.npmrc"
    - "/home/{{ admin_user }}/.pam_environment"
    - "/home/{{ admin_user }}/.xinitrc"
    - "/home/{{ admin_user }}/.zlogin"
    - "/home/{{ admin_user }}/.zprofile"
    - "/home/{{ admin_user }}/.zshrc"
    #- "/home/{{ admin_user }}/"
    #- "/home/{{ admin_user }}/"

- name: clone dotfiles git repo
  git:
    repo: "{{ github_dotfiles_repo }}"
    dest: "/home/{{ admin_user }}/.cfg"
    clone: yes
    key_file: "/home/{{ admin_user }}/.ssh/github"
    force: yes
    bare: yes
    accept_hostkey: yes
  become: yes
  become_user: "{{ admin_user }}"
  become_method: sudo

- name: checkout dotfiles git repo
  command: "/usr/bin/git --git-dir=/home/{{ admin_user }}/.cfg --work-tree=/home/{{ admin_user }} checkout"
  become: yes
  become_user: "{{ admin_user }}"
  become_method: sudo
