# entry point for the setup_arch_base role

---
- include_tasks: prepare-live-environment.yml
- include_tasks: partition-efi.yml
  when: use_efi
- include_tasks: partition-legacy-bios.yml
  when: not use_efi
- include_tasks: setup-LUKS.yml
- include_tasks: volumes.yml
