---
# the ansible command module is used here because the parted module seems to be broken (as of Jan 2020)
- name: create gpt partition table
  block:
    # -s: --script
    - name: partition disk
      command: parted -s {{ grub_device|quote }} mklabel gpt
  rescue:
    - name: wipe disk and reboot
      include_tasks: wipe-disk-and-reboot.yml
    - name: attempt to partition disk again
      command: parted -s {{ grub_device|quote }} mklabel gpt

- name: create+flag efi_part partition
  # efi_partition is always first
  shell: |
    parted -s {{ grub_device|quote }} mkpart efi_part 0% {{ efi_size }}MiB
    parted -s {{ grub_device|quote }} set 1 boot on
    parted -s {{ grub_device|quote }} set 1 esp on

# - name: create+flag swap partition
#   # will not be marked as swap for plain encryption
#   shell: |
#     parted -s {{ grub_device|quote }} mkpart swap_part {{ efi_size }}MiB {{ efi_size + swap_size }}MiB
## I will use a swapfile instead

- name: create system partition
  command: parted -s {{ grub_device|quote }} mkpart sys_part {{ efi_size }}MiB 100%
