---
# the ansible command module is used here because the parted module seems to be broken (as of Jan 2020)

- name: get partition table status
  parted:
    device: "{{ grub_device }}"
    state: info
    unit: MiB
  register: disk_info

- debug:
    msg: "{{ disk_info }}"

- name: create gpt partition table
  command: parted -s {{ grub_device|quote }} mklabel gpt
  when: disk_info['disk']['table'] == 'unknown'

- name: create+flag efi_part partition
  block:
    - name: efi_part create
      command: parted -s {{ grub_device|quote }} mkpart efi_part 1MiB {{ efi_size + 1 }}MiB
    - name: efi_part flag boot
      command: parted -s {{ grub_device|quote }} set 1 boot on
    - name: efi_part flag esp
      command: parted -s {{ grub_device|quote }} set 1 esp on
  when: disk_info['partitions'] | length == 0 or
        disk_info['partitions'][0]['size'] != {{ efi_size|float }} or
        disk_info['partitions'][0]['name'] != 'efi_part' or
        disk_info['partitions'][0]['flags'][0] != 'boot' or
        disk_info['partitions'][0]['flags'][1] != 'esp'

- name: get partition table status
  parted:
    device: "{{ grub_device }}"
    state: info
    unit: MiB
  register: disk_info

- name: create+flag swap_part partition
  block:
    - name: swap_part create
      command: parted -s {{ grub_device|quote }} mkpart swap_part {{ efi_size + 1 }}MiB {{ efi_size + swap_size + 1 }}MiB
    - name: swap_part flag swap
      command: parted -s {{ grub_device|quote }} set 2 swap on
  when: disk_info['partitions']|length == 1 or
        disk_info['partitions'][1]['size'] != {{ swap_size|float }} or
        disk_info['partitions'][1]['name'] != 'swap_part' or
        disk_info['partitions'][1]['flags'][0] != 'swap'

- name: get partition table status
  parted:
    device: "{{ grub_device }}"
    state: info
    unit: MiB
  register: disk_info

- name: create sys_part partition
  command: parted -s {{ grub_device|quote }} mkpart sys_part {{ efi_size + swap_size + 1 }}MiB 100%
  when: disk_info['partitions']|length == 2 or
        disk_info['partitions'][2]['name'] != 'sys_part'
