---
# steps to prepare the live environment before desktop setup

- name: "set /etc/hostname on live-env"
  template:
    src: hostname.j2
    dest: "/etc/hostname"

- name: lock hostname on live-env
  command: hostname -F /etc/hostname

- name: update system clock
  command: /usr/bin/timedatectl set-ntp true

- name: create temporary ansible directory
  tempfile:
    state: directory
    prefix: autoarch.
  register: tmpdir0

- name: make a vault directory inside the ansible directory
  file:
    path: "{{ tmpdir0.path }}/vault"
    state: directory
    mode: '0760'
