---
# steps to prepare the live environment before desktop setup

- name: "set /etc/hostname on live-env"
  template:
    src: etc/hostname.j2
    dest: "/etc/hostname"
  notify: lock hostname

- name: update system clock
  command: /usr/bin/timedatectl set-ntp true

- name: create temporary ansible directory
  file:
    state: directory
    path: "{{ tmpdir0 }}"
    mode: '0700'

- name: make a vault directory inside the ansible directory
  file:
    path: "{{ tmpdir0 }}/vault"
    state: directory
    mode: '0760'

- name: create the sys_mount mount point
  file:
    path: "{{ sys_mount }}"
    state: directory
    mode: '0760'
