# file: setup-LUKS.yml
# sets up LUKS on stated partitions

- name: transfer keyfile
  copy:
    src: "./vault/{{ luks_keyfile }}"
    dest: "{{ tmpdir0.path }}/vault"
    mode: '0700'

- name: create LUKS container on system partition
  luks_device:
    device: "{{ system_part }}"
    state: present
    keyfile: "{{ tmpdir0.path }}/vault/{{ luks_keyfile }}"
