# file: setup-LUKS.yml
# sets up LUKS on stated partitions

- name: transfer keyfile
  copy:
    src: "./vault/{{ luks_keyfile }}"
    dest: "{{ tmpdir0 }}/vault"
    mode: '0700'
    decrypt: yes

- name: create LUKS container on system partition
  luks_device:
    device: "{{ system_part }}"
    state: present
    keyfile: "{{ tmpdir0 }}/vault/{{ luks_keyfile }}"
