# file: volumes.yml
# creates a btrfs volume on the system partition.
# Other partitions will be simulated as btrfs subvolumes
---
- name: open LUKS container for system partition
  luks_device:
    state: opened
    device: "{{ system_part }}"
    keyfile: "{{ tmpdir0 }}/vault/{{ luks_keyfile }}"
    name: "{{ luks_syspart_name}}"

- name: create btrfs flat layout
  include_tasks: ./roles/setup_arch_base/tasks/btrfs-layout-flat/create.yml
  vars:
    device: "/dev/mapper/{{ luks_syspart_name}}"
    mountpoint: "{{ sys_mount }}"

- name: create /efi mount point
  file:
    state: directory
    path: "{{ sys_mount }}/efi"
    mode: '0700'
  when: use_efi

- name: create filesystem on efi_part
  filesystem:
    dev: "{{ efi_part }}"
    fstype: vfat
    force: yes

- name: create filesystem on swap_part
  filesystem:
    dev: "{{ swap_part }}"
    fstype: swap
    force: no
