# file: volumes.yml
# creates a btrfs volume on the system partition.
# Other partitions will be simulated as btrfs subvolumes
---
- name: open LUKS container for system partition
  luks_device:
    state: opened
    device: "{{ system_part }}"
    keyfile: "{{ tmpdir0 }}/vault/{{ luks_keyfile }}"
    name: "{{ inventory_hostname }}_{{ luks_syspart_name}}"

- name: create btrfs flat layout and mount it the btrfs way
  include_tasks: ./roles/setup_arch_base/tasks/btrfs-layout-flat/create.yml
  vars:
    device: "/dev/mapper/{{ inventory_hostname }}_{{ luks_syspart_name}}"
    mountpoint: "{{ sys_mount }}"

- name: create /efi mount point
  file:
    state: directory
    path: /efi
    mode: '0700'
  when: use_efi
