# file: archpkg_local_aurutils/tasks/main.yml
# installs aurutils (package manager for the AUR) from a local package
---

- name: create builds directory in user home
  file:
    path: "/home/{{ admin_user }}/builds"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"

- name: copy aurutils package to ~/builds directory
  copy:
    src: "files/builds/aurutils-2.3.3-1-any.pkg.tar.xz"
    dest: "/home/{{ admin_user }}/builds"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"

- name: install aurutils package
  pacman:
    name:
      - diffstat
      - expac
      - pacutils
      - parallel
      - "/home/{{ admin_user}}/builds/aurutils-2.3.3-1-any.pkg.tar.xz"
    state: present
