# file: arch_aurutils_repo/tasks/main.yml
# sets up a local pacman repository for the aur. Is intended to be used with aurutils.
---

# contains location of he local repo: /var/local/custompkgs
- name: copy pacman.conf
  copy:
    src: etc/pacman.conf
    dest: /etc/pacman.conf
    mode: '0644'
    force: yes

- name: create local cache directory
  file:
    path: /var/cache/pacman/custom
    state: directory
    force: yes
    mode: '0644'

- name: create the repo directory
  file:
    path: /var/local/custompkgs
    state: directory
    force: yes
    mode: '0644'

- name: create the repo database
  command: repo-add /var/local/custompkgs/custom.db.tar.gz
