use_efi: yes
use_LUKS: yes
grub_device: /dev/sda
efi_part: /dev/sda1
swap_part: /dev/sda2
system_part: /dev/sda3

# size in MiB
#efi_size: 256
#swap_size: 8192
efi_size: 128
swap_size: 128

luks_keyfile: wife_syskey
luks_syspart_name: syspart_crypt
sys_mount: /mnt/arch_root

rootpw: "$6$mysecretsalt$hvehUWS5j6XEiiB31rDew6.byx3i57VmHbJ1YNzOa4/l/cQWS3ox8cDKmjtn14KdE.5Bb/RH6u57YdzHlCHyE/"
