# file: arch_aurutils_repo/tasks/main.yml
# sets up a local pacman repository for the aur. Is intended to be used with aurutils.
---

# contains location of he local repo: /var/local/custompkgs
- name: copy pacman.conf
  copy:
    src: etc/pacman.conf
    dest: /etc/pacman.conf
    mode: '0644'
    force: yes

- name: create the repo database
  command: repo-add /var/cache/pacman/builder/custom.db.tar.xz
  become: yes
  become_user: builder
  become_method: sudo
