# file: btrfs-layout-flat/create.yml
---
- debug:
    msg: "creating a btrfs filesystem with flat subvolume layout"


- name: create btrfs filesystem on the system partition
  filesystem:
    dev: "{{ device }}"
    fstype: btrfs
    force: yes


# mount system partition to create the btrfs filesystem with the desired subvolumes
- name: mount the mapped filesystem
  command: mount -t btrfs -o compress=zstd {{ device }} {{ mountpoint }}


- name: create the btrfs root subvolume
  command: btrfs subvolume create {{ mountpoint }}/@


- name: create the btrfs home subvolume
  command: btrfs subvolume create {{ mountpoint }}/@home


- name: create the btrfs snapshots subvolume
  command: btrfs subvolume create {{ mountpoint }}/@snapshots


# subvolumes, which are not directly under root so not to be snapshotted
- name: mkdir /var/cache/pacman and parent directories
  command: mkdir -p {{ mountpoint }}/var/cache/pacman


- name: create the btrfs pacman cache subvolume
  command: btrfs subvolume create {{ mountpoint }}/var/cache/pacman/@pkg


- name: create the btrfs abs subvolume
  command: btrfs subvolume create {{ mountpoint }}/var/@abs


- name: create the btrfs tmp subvolume
  command: btrfs subvolume create {{ mountpoint }}/var/@tmp


# unmounting the partition to remount it with the subvolumes
- name: unmount the system partition
  command: umount {{ mountpoint }}
