# file: btrfs-layout-flat/mount.yml
# layout specific mounting of btrfs subvolumes
---
# This file uses local variables defined in the calling context.
- debug:
    msg: "mounting the btrfs flat layout, device: {{ device }}, mountpoint: {{ mountpoint }}"

- name: mount subvolume @ on /
  command: mount -o compress=zstd,subvol=@ {{ device }} {{ mountpoint }}

- name: mount subvolume @home on /home
  command: mount -o compress=zstd,subvol=@home {{ device }} {{ mountpoint }}/home

- name: mount subvolume @snapshots on /.snapshots
  command: mount -o compress=zstd,subvol=@snapshots {{ device }} {{ mountpoint }}/.snapshots
